name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Determine App File Paths
        id: app_files
        run: |
          if [ -n "$(find . -type f -name '*.exe')" ]; then
            echo "::set-output name=windows_file::$(find . -type f -name '*.exe')"
          fi
          if [ -n "$(find . -type f -name '*.dmg')" ]; then
            echo "::set-output name=mac_file::$(find . -type f -name '*.dmg')"
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files:
            windows: ${{ steps.app_files.outputs.windows_file }}
            mac: ${{ steps.app_files.outputs.mac_file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ steps.create_release.outputs.upload_url }}
