name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: electron-build-artifact
          path: dist/**  # Assuming the build output is in the 'dist' directory

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: electron-build-artifact

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release-${{ github.sha }}
          draft: false
          prerelease: false
          body: "Release of commit ${{ github.sha }}"