name: Build & Release

on:
  push:
    branches:
      - release # Trigger only on push to the release branch

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Generate random tag from commit
        id: randomtag
        run: echo "::set-output name=TAG::$(echo ${{ github.sha }} | md5sum | head -c 8)" # Generate an 8 character tag

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          # Set the tag to the generated random string
          tag: ${{ steps.randomtag.outputs.TAG }}