name: Build & Release

on:
  push:
    branches:
      - release # Trigger only on push to the release branch

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Generate random tag from commit
        id: randomtag
        run: echo "RANDOM_TAG=$(echo ${{ github.sha }} | md5sum | head -c 8)" >> $GITHUB_ENV

      - name: Create a new tag
        run: git tag ${{ env.RANDOM_TAG }} ${{ github.sha }}

      - name: Push the tag to GitHub
        run: git push origin ${{ env.RANDOM_TAG }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/heads/release') }}
